services:
  # SonarQube Database
  sonarqube-db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    networks:
      secnet:
        ipv4_address: "172.30.0.101"

  # SonarQube Server
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - ./code:/opt/sonarqube/src
    networks:
      secnet:
        ipv4_address: "172.30.0.102"

  # SonarScanner
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-scanner
    volumes:
      - ./code:/usr/src 
      - ./reports:/reports
    depends_on:
      - sonarqube
    command: >
      sh -c "
        tail -f /dev/null
      "
    networks:
      secnet:
        ipv4_address: "172.30.0.103"

  # Semgrep (run manually via exec)
  semgrep:
    image: returntocorp/semgrep
    container_name: semgrep
    volumes:
      - ./code:/src
      - ./reports:/reports
    command: >
      sh -c "
        tail -f /dev/null
      "
    networks:
      secnet:
        ipv4_address: "172.30.0.104"

  # Code Cloner
  code-collector:
    image: alpine/git
    container_name: code-collector
    volumes:
      - ./code:/workspace
      - ./clone.sh:/clone.sh
    working_dir: /workspace
    entrypoint: /bin/sh
    command: >
      -c "
        echo 'Running clone.sh...';
        chmod +x /clone.sh && /clone.sh;
        echo 'Clone script completed.';
        tail -f /dev/null
      "
    networks:
      secnet:
        ipv4_address: "172.30.0.105"

networks:
  secnet:
    name: secnet-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_db_data: